### ISSUE TITLE
Aedes-Node not showing up in palette after installation

### ISSUE THREAD

**Issue by Mantikor1** [martin-doyle/node-red-contrib-aedes#65]
Hello everyone,

i tried installing the node with the palette manager and npm, but had no success yet. After the installation the node doesn't show up in the palette but gets listed as installed.

Installing the node with the npm command gives me the following response:

```
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
+ node-red-contrib-aedes@0.8.2
added 73 packages from 100 contributors and audited 75 packages in 90.744s
found 0 vulnerabilities
```

Does this issue prevent the node from working entirely? I'm working with older versions of node and node-red, is the aedes-node not compatible?

My versions are:
node version is 8.16.1
node-red version is 1.2.9

Any help would be appreciated!

**Comment by martin-doyle** [comment]
In the package.json there are 2 entries: node-red.version >=2.0.0 and engines.node >= 12.0.0.
I added those in order to get a good scorecard. Unfortunately, the scorecard still shows missing information about node and Node-RED version. 
I assume this prevents the node from showing up in your installation since your versions are really old.

**Comment by Mantikor1** [comment]
Thanks for the clarification. After trying to install the node through the palette it also showed the needed versions in the debug panel.
Since my machine doesn' support newer versions of node-red or node.js I installed the mosquitto-broker directly.
